# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Alert' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SCLAlertView'
  # Pods for Alert

end
