source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'image' do
pod 'SwiftyJSON'
pod 'Alamofire', '~> 3.4'
pod 'SDWebImage', '~>3.7'
end

